<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-1T2AMDB" ignored="3" name="Default test" tests="3" failures="1" timestamp="2021-01-17T21:04:36 IST" time="50.115" errors="0">
  <testcase name="verifyContactUseLink" time="8.14" classname="TestCases.Home_Contactus_PageVerification_001">
    <skipped/>
  </testcase> <!-- verifyContactUseLink -->
  <testcase name="verifyContactUseLink" time="8.126" classname="TestCases.Home_Contactus_PageVerification_001">
    <skipped/>
  </testcase> <!-- verifyContactUseLink -->
  <testcase name="verifyContactUseLink" time="7.636" classname="TestCases.Home_Contactus_PageVerification_001">
    <failure type="java.lang.AssertionError" message="expected [CUSTOMER SERVICE - CONTACT US ] but found [CUSTOMER SERVICE - CONTACT US]">
      <![CDATA[java.lang.AssertionError: expected [CUSTOMER SERVICE - CONTACT US ] but found [CUSTOMER SERVICE - CONTACT US]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestCases.Home_Contactus_PageVerification_001.verifyContactUseLink(Home_Contactus_PageVerification_001.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyContactUseLink -->
  <testcase name="sendMessage_UploadusingSendKeys" time="0.0" classname="TestCases.Home_Contactus_PageVerification_001">
    <ignored/>
  </testcase> <!-- sendMessage_UploadusingSendKeys -->
  <testcase name="Monster_FileUploadUsingRobotClass" time="0.0" classname="TestCases.Home_Contactus_PageVerification_001">
    <ignored/>
  </testcase> <!-- Monster_FileUploadUsingRobotClass -->
  <testcase name="homeButtonVerification" time="0.0" classname="TestCases.Home_Contactus_PageVerification_001">
    <ignored/>
  </testcase> <!-- homeButtonVerification -->
</testsuite> <!-- Default test -->
